messages:
  join: "Welcome {player} to the server!"
  quit: "Goodbye {player}, see you next time!"
  # To set Color or make ist Bold use / ยง<ColorCode>
  # You can get the Color Codes here https://minecraft.tools/de/color-code.php